// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmZFt-iCpZNi2L11eZEbMwvoytupMJjls',
    appId: '1:383400116638:web:cfb52f242848c9e986168f',
    messagingSenderId: '383400116638',
    projectId: 'flutter-rappiu',
    authDomain: 'flutter-rappiu.firebaseapp.com',
    storageBucket: 'flutter-rappiu.firebasestorage.app',
    measurementId: 'G-RKTDGHT25M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqV_omGfMSW7uo8oYMNoG3Qip2oun3MzY',
    appId: '1:383400116638:android:0953fe800c244ad486168f',
    messagingSenderId: '383400116638',
    projectId: 'flutter-rappiu',
    storageBucket: 'flutter-rappiu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqfE50MWTaYuq1RgwBDG6qidBSg-Pf8EE',
    appId: '1:383400116638:ios:6d3a21170034a5a186168f',
    messagingSenderId: '383400116638',
    projectId: 'flutter-rappiu',
    storageBucket: 'flutter-rappiu.firebasestorage.app',
    iosBundleId: 'com.example.delieveru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqfE50MWTaYuq1RgwBDG6qidBSg-Pf8EE',
    appId: '1:383400116638:ios:6d3a21170034a5a186168f',
    messagingSenderId: '383400116638',
    projectId: 'flutter-rappiu',
    storageBucket: 'flutter-rappiu.firebasestorage.app',
    iosBundleId: 'com.example.delieveru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmZFt-iCpZNi2L11eZEbMwvoytupMJjls',
    appId: '1:383400116638:web:9aa1c8336592e45086168f',
    messagingSenderId: '383400116638',
    projectId: 'flutter-rappiu',
    authDomain: 'flutter-rappiu.firebaseapp.com',
    storageBucket: 'flutter-rappiu.firebasestorage.app',
    measurementId: 'G-YCK7K0SC4X',
  );

}